name: PR Labeler

on:
  pull_request:
    types: [ opened, edited, synchronize ]

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    name: Label Pull Request
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Auto-label based on files
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
    
    - name: Label based on PR size
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr = context.payload.pull_request;
          const additions = pr.additions;
          const deletions = pr.deletions;
          const total = additions + deletions;
          
          let size = '';
          if (total < 10) size = 'size/XS';
          else if (total < 50) size = 'size/S';
          else if (total < 250) size = 'size/M';
          else if (total < 1000) size = 'size/L';
          else size = 'size/XL';
          
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            labels: [size]
          });
